"""skilltree map — render a flat folder into ONE coordinate-addressed CLAUDE.md.

Folds the former `skillmap` seedling into skilltree as a module. It mirrors a folder's
directory nesting as a tree, gives every node a hierarchical coordinate, and writes a single
CLAUDE.md — a Folder Map + an addressable Index + branch summaries — so an agent can do
*progressive disclosure* over a flat pile (open a branch, descend to the coordinate it needs)
instead of loading all of it.

It uses skilltree's OWN coordinate code — `assign_coords` / `skill_name` / `compose_summary`
from `model.py`. There is no vendored copy: one source of truth for the `<coord>-<name>` scheme.

    skilltree map ~/.claude/skills            # print the map
    skilltree map ~/.claude/skills --write     # write CLAUDE.md into the folder
"""
from __future__ import annotations

import re
from pathlib import Path

from .model import TreeNode, assign_coords, compose_summary, skill_name

_DESC = re.compile(r"^description:\s*(.+)$", re.I | re.M)


def read_description(d: Path) -> str:
    """Best-effort one-line description for a directory node: the `description:` frontmatter of
    SKILL.md/README, else the first real line/heading of any markdown in the dir."""
    for fn in ("SKILL.md", "README.md"):
        f = d / fn
        if f.is_file():
            txt = f.read_text(encoding="utf-8", errors="ignore")
            m = _DESC.search(txt)
            if m:
                return m.group(1).strip().strip("\"'")[:160]
            for line in txt.splitlines():
                s = line.strip()
                if s and not s.startswith("---"):
                    return s.lstrip("# ").strip()[:160]
    for f in sorted(d.glob("*.md")):
        for line in f.read_text(encoding="utf-8", errors="ignore").splitlines():
            s = line.strip()
            if s and not s.startswith("---"):
                return s.lstrip("# ").strip()[:160]
    return ""


def build_tree(folder: str | Path) -> TreeNode:
    """Mirror the directory nesting as skilltree `TreeNode`s. A node = a subdirectory; the dir
    path rides in `skill_src`. Hidden dirs (dotfiles) are skipped."""
    root_path = Path(folder)
    root = TreeNode(name=root_path.name, kind="sc", description="(root)", skill_src=str(root_path))

    def add(parent: TreeNode) -> None:
        for d in sorted(p for p in Path(parent.skill_src).iterdir()
                        if p.is_dir() and not p.name.startswith(".")):
            child = TreeNode(name=d.name, kind="skill",
                             description=read_description(d) or None, skill_src=str(d))
            parent.children.append(child)
            add(child)

    add(root)
    return root


def _folder_map(root: TreeNode) -> str:
    lines = [f"{root.coord}  {root.name}/"]

    def rec(node: TreeNode, prefix: str) -> None:
        n = len(node.children)
        for i, c in enumerate(node.children):
            last = i == n - 1
            branch = "└─ " if last else "├─ "
            desc = f"  — {c.description}" if c.description else ""
            lines.append(f"{prefix}{branch}{c.coord}  {c.name}{desc}")
            rec(c, prefix + ("   " if last else "│  "))

    rec(root, "")
    return "\n".join(lines)


def _index(root: TreeNode) -> str:
    rp = Path(root.skill_src)
    rows = ["| Coord | Skill | Address | What it does | Path |", "|---|---|---|---|---|"]
    for n in root.walk():
        if n is root:
            continue
        rel = Path(n.skill_src).relative_to(rp)
        rows.append(f"| `{n.coord}` | {n.name} | `{skill_name(n)}` | {n.description or '—'} | `{rel}/` |")
    return "\n".join(rows)


def _branches(root: TreeNode) -> str:
    rows = [f"- `{n.coord}` **{n.name}** → {compose_summary(n)}"
            for n in root.walk() if n.children]
    return "\n".join(rows) or "_(flat — every skill is a leaf at depth 1)_"


def build_map(folder: str | Path) -> str:
    """Render the folder as ONE coordinate-addressed CLAUDE.md (Folder Map + Index + Branches)."""
    root = assign_coords(build_tree(folder))
    nodes = list(root.walk())
    n_skills = len(nodes) - 1
    depth = max((n.coord.count(".") for n in nodes), default=0)
    return (f"# {root.name} — skill map\n\n"
            f"*Auto-generated by `skilltree map`. {n_skills} skills, depth {depth}. Each skill has a "
            f"coordinate address — open a branch, descend to the coordinate you need. Don't load the "
            f"whole pile; navigate it.*\n\n"
            f"## Folder Map\n\n```\n{_folder_map(root)}\n```\n\n"
            f"## Index (addressable)\n\n{_index(root)}\n\n"
            f"## Branches (what each opens to)\n\n{_branches(root)}\n")


def write_map(folder: str | Path) -> Path:
    """Write the map to `<folder>/CLAUDE.md`; returns the path."""
    dest = Path(folder) / "CLAUDE.md"
    dest.write_text(build_map(folder), encoding="utf-8")
    return dest
